### ISSUE TITLE
Report, summary table, paging and episode selection

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#109]
~@farski I'm also a little unclear what goes in the table on the different chart scenarios. On the one shown in the mockup, is that a listing of all of the podcasts episodes with the total downloads during the date range, release date, daily average, and all time downloads? Will that table change at all based on what type of chart is shown?~
@farski do averages change based on the interval selected? The mockup shows daily averages with the daily interval, so will those be hourly, weekly, or monthly with our other intervals?

A paged table will be shown with the pages ordered by release date. 
* [ ] The page size is 10
* [ ] On chart types that show individual episode data, there will be fancy checkboxes that also double as a legend to allow the user to toggle on or off each of the episodes from appearing in the chart
* [ ] A summary view with Total during the period, average, and all time downloads will be the default table view
* [ ] The user can select to expand out the table to also show the report breakdown containing each of the individual data points.
  * [ ] A Google Analytics event will be tied to this toggle so we can see how often users are looking at the reports

The table is not (yet?) sortable or searchable. However further questions we had for iterating on this approach is if there is some way to interact with the table, a filter or a go to page (more indicated by release date or episode title rather than requiring mental math with a page number), that allows the user to seek directly to an episode or set of episodes that they want to see that may have been released some time ago and further back in the pages.

**Comment by sandikbarr** [comment]
implementation notes: to get the total all time downloads, Castle has to be running with rollups against BQ prod. `downloads.total` is available at the `/api/v1/episodes/:guid` or `/api/v1/podcasts/:id` endpoint.
