### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#19]
* [ ] Chart showing downloads per chosen interval (not cumulative)
* [ ] User can select which episodes are to be charted. Options include Last 5 Released, Last 10 Released, All Others/All Episodes. When some episodes are selected, the option is "All Others"; when no other episodes are selected, the option is "All Episodes". All Episodes will chart at the podcast level, not the individual episode level.
* [ ] Default view shows Last 5 Released Episodes as part of the total downloads, so Last 5 Released with All Others
* [ ] User can adjust date range or select from a set of canned date ranges
* [ ] ~Default date range will be adjusted according to how long the most recent episode has been out~
* [ ] User can adjust interval- 15min, hourly, daily, weekly, monthly (weekly and monthly not yet available in castle)
* [ ] If this week, two weeks, last week, etc canned date ranges are chosen, weeks begin on Sunday 12am UTC
* [ ] Provide table view of downloads data. To reach feature parity with podtrac, we need to show all of the episodes in the table view, not just the last 5 released or just what is currently in the chart. Performance still needs to be proven on whether we should provide this in a default view, so perhaps this feature can be toggled on.

**Comment by sandikbarr** [comment]
@pkarman depending on how we actually prioritize this (as in are we gonna try to get all this done in this short sprint or also work on other things,) I could see making this into an epic and breaking it down into separate tickets.
